name: envdecoil
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python==3.8.0
  - survivor==1.0.7
  - sniffles>=1.0.7,<=1.0.12
  - ngmlr==0.2.7
  - ncurses==6.1
  - samtools==1.9
  - nanofilt==2.6.0
  - python-dateutil==2.8.0
  - pip==22.2.2