name: envdecoil
channels:
  - bioconda
  - conda-forge
dependencies:
  - python==3.10
  - pip==24.2
  - survivor==1.0.7
  - sniffles==1.0.12
  - savana==1.2.2
  - ngmlr==0.2.7
  - samtools==1.15.1
  - python-dateutil==2.8.1
  - deeptools==3.5.5
